chore: force vulnerability check step to always run

diff --git a/.github/workflows/snyk-security.yml b/.github/workflows/snyk-security.yml
--- a/.github/workflows/snyk-security.yml
+++ b/.github/workflows/snyk-security.yml
@@ -114,10 +114,15 @@ jobs:
           path: ${{ matrix.project }}/snyk-open-source.sarif
           retention-days: 7
       - name: Fail if vulnerabilities found
-        if: env.SNYK_EXIT_CODE != '0'
+        if: always()
         run: |
-          echo "::error::Snyk found vulnerabilities or encountered an error. Exit code: $SNYK_EXIT_CODE"
-          exit $SNYK_EXIT_CODE
+          if [ "$SNYK_EXIT_CODE" != "0" ]; then
+            echo "::error::Snyk found vulnerabilities or encountered an error. Exit code: $SNYK_EXIT_CODE"
+            exit $SNYK_EXIT_CODE
+          else
+            echo "No vulnerabilities found! Exit code: 0"
+            exit 0
+          fi
 
   snyk-monorepo:
     name: Repository-Wide Scan
@@ -182,8 +187,15 @@ jobs:
           path: snyk-code.sarif
           retention-days: 7
       - name: Fail if vulnerabilities found
-        if: env.SNYK_EXIT_CODE != '0'
-        run: exit $SNYK_EXIT_CODE
+        if: always()
+        run: |
+          if [ "$SNYK_EXIT_CODE" != "0" ]; then
+            echo "::error::Snyk found vulnerabilities or encountered an error. Exit code: $SNYK_EXIT_CODE"
+            exit $SNYK_EXIT_CODE
+          else
+            echo "No vulnerabilities found! Exit code: 0"
+            exit 0
+          fi
 
   snyk-iac:
     name: Terraform Scan
@@ -228,8 +240,15 @@ jobs:
           path: snyk-iac.sarif
           retention-days: 7
       - name: Fail if vulnerabilities found
-        if: steps.check_tf.outputs.has_tf == 'true' && env.SNYK_EXIT_CODE != '0'
-        run: exit $SNYK_EXIT_CODE
+        if: steps.check_tf.outputs.has_tf == 'true' && always()
+        run: |
+          if [ "$SNYK_EXIT_CODE" != "0" ]; then
+            echo "::error::Snyk found vulnerabilities or encountered an error. Exit code: $SNYK_EXIT_CODE"
+            exit $SNYK_EXIT_CODE
+          else
+            echo "No vulnerabilities found! Exit code: 0"
+            exit 0
+          fi
 
   snyk-monitor:
     name: Snyk Monitor
